CREATE TABLE Author (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(64) NOT NULL,
	[Pseudo] NVARCHAR(48)
);


CREATE TABLE Genre (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(64) NOT NULL,
	[Description] NVARCHAR(256)
);


CREATE TABLE Publisher (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Id_City] INT NOT NULL,
	[Name] NVARCHAR(64) NOT NULL
);

CREATE TABLE City (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(32) NOT NULL
);

CREATE TABLE Book (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Id_Author] INT NOT NULL,
	[Id_Genre] INT NOT NULL,
	[Id_Publisher] INT NOT NULL,
	[Title] NVARCHAR(128) NOT NULL,
	[Annotation] NVARCHAR(MAX) NOT NULL,
	[Year] INT NOT NULL,
	[Price] MONEY NOT NULL,
	[Pages] INT NOT NULL,
	[Cover_file] NVARCHAR(256)
);


--ALTER TABLE Book ADD FOREIGN KEY ([Id_Author]) REFERENCES Author([Id]) ON DELETE CASCADE ON UPDATE CASCADE;
--ALTER TABLE Book ADD FOREIGN KEY ([Id_Genre]) REFERENCES Genre([Id]) ON DELETE CASCADE ON UPDATE CASCADE;
--ALTER TABLE Book ADD FOREIGN KEY ([Id_Publisher]) REFERENCES Publisher([Id]) ON DELETE CASCADE ON UPDATE CASCADE;
--ALTER TABLE Publisher ADD FOREIGN KEY ([Id_City]) REFERENCES City([Id]) ON DELETE CASCADE ON UPDATE CASCADE;