CREATE TABLE Users (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Login] VARCHAR(32) NOT NULL,
	[PassHash] CHAR(64) NOT NULL,
	[RealName] NVARCHAR(64),
	[LastVisit] DATETIME,
	[RegDT] DATETIME NOT NULL
)